# Uncomment the next line to define a global platform for your project
 platform :ios, '10.2'

target 'FirebaseCRUDExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseCRUDExample
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
